In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [2]:
iris=load_iris()

In [12]:
score_1=cross_val_score(LogisticRegression(),iris.data,iris.target)
score_1

C:\Users\OWNER\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [13]:
import numpy as np


In [14]:
np.average(score_1)

0.9733333333333334

In [15]:
score_2=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
np.average(score_2)

0.9666666666666668

In [16]:
score_3=cross_val_score(SVC(),iris.data,iris.target)
np.average(score_3)

0.9666666666666666

In [17]:
score_3

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [20]:
score_4=cross_val_score(RandomForestClassifier(n_estimators=50),iris.data,iris.target)
score_4

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [21]:
np.average(score_4)

0.96